import {
  Bell,
  Copyright,
  LogOut,
  UserRound,
  CircleCheck,
  House,
  CirclePlus,
  Brain,
  CircleX,
  Clock,
  Search,
  Dumbbell,
  ChevronDown,
  ChevronUp,
  CalendarCheck,
  RotateCcw,
  NotepadText,
  ArrowRight,
  ArrowLeft,
  Pause,
  Play,
  Goal,
  Trophy,
} from "lucide-react";

const Icons = {
  bell: Bell,
  user: UserRound,
  copyright: Copyright,
  logout: LogOut,
  check: CircleCheck,
  uncheck: CircleX,
  home: House,
  add: CirclePlus,
  ai: Brain,
  clock: Clock,
  search: Search,
  dumbell: Dumbbell,
  expand: ChevronDown,
  collapse: ChevronUp,
  calendar: CalendarCheck,
  repeat: RotateCcw,
  log: NotepadText,
  right: ArrowRight,
  left: ArrowLeft,
  pause: Pause,
  play: Play,
  goal: Goal,
  trophy: Trophy
};

export default Icons;
