import {
  Bell,
  Copyright,
  LogOut,
  UserRound,
  CircleCheck,
  House,
  CirclePlus,
  Brain,
  CircleX,
  Clock,
  Search,
  Dumbbell,
  ChevronDown,
  ChevronUp,
  CalendarCheck,
  RotateCcw,
  NotepadText,
  ArrowRight,
  ArrowLeft,
  Pause,
  Play,
  Goal,
  Trophy,
  Sparkles,
  Edit,
  FlagOff,
  Eye,
  MessageSquare,
  Heart,
  Share2,
  SendHorizonal,
  Trash,
  Info,
  Menu,
  Funnel,
  FunnelX,
  UserSearch,
  UserPlus,
  Zap,
  ChartColumnIncreasing,
  Users,
} from "lucide-react";

const Icons = {
  bell: Bell,
  user: UserRound,
  menu: Menu,
  filter: Funnel,
  removeFilter: FunnelX,
  copyright: Copyright,
  logout: LogOut,
  check: CircleCheck,
  uncheck: CircleX,
  home: House,
  add: CirclePlus,
  edit: Edit,
  ai: Brain,
  clock: Clock,
  search: Search,
  dumbell: Dumbbell,
  expand: ChevronDown,
  collapse: ChevronUp,
  calendar: CalendarCheck,
  repeat: RotateCcw,
  log: NotepadText,
  right: ArrowRight,
  left: ArrowLeft,
  pause: Pause,
  play: Play,
  goal: Goal,
  trophy: Trophy,
  sparkle: Sparkles,
  abandon: FlagOff,
  view: Eye,
  comment: MessageSquare,
  like: Heart,
  share: Share2,
  send: SendHorizonal,
  delete: Trash,
  info: Info,
  userSearch: UserSearch,
  userSuggestion: UserPlus,
  bolt: Zap,
  chart: ChartColumnIncreasing,
  users: Users,
};

export default Icons;
